### ISSUE TITLE
nil pointer

### ISSUE THREAD

**Issue by qydysky** [qydysky/bili_danmu#78]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9c93d0]
goroutine 35572 [running]:
container/list.(*List).insert(...)
	/opt/hostedtoolcache/go/1.20.6/x64/src/container/list/list.go:96
container/list.(*List).insertValue(...)
	/opt/hostedtoolcache/go/1.20.6/x64/src/container/list/list.go:104
container/list.(*List).PushBack(...)
	/opt/hostedtoolcache/go/1.20.6/x64/src/container/list/list.go:152
github.com/qydysky/part/msgq.(*MsgType[...]).register(0xc14e80, 0xc00057e000)
	/home/runner/go/pkg/mod/github.com/qydysky/part@v0.28.1-0.20230726013256-40eba56c6e85/msgq/Msgq.go:343 +0x130
github.com/qydysky/part/msgq.(*MsgType[...]).Pull_tag_only(0xc14e80?, {0xb13e6c, 0x7}, 0xc000488010)
	/home/runner/go/pkg/mod/github.com/qydysky/part@v0.28.1-0.20230726013256-40eba56c6e85/msgq/Msgq.go:448 +0xb6
github.com/qydysky/bili_danmu/Reply.(*M4SStream).Start.func1.3(0xc00035c360)
	/home/runner/work/bili_danmu/bili_danmu/Reply/stream.go:1185 +0xe5
github.com/qydysky/part/msgq.(*MsgType[...]).Pull_tag_async.func1.1()
	/home/runner/go/pkg/mod/github.com/qydysky/part@v0.28.1-0.20230726013256-40eba56c6e85/msgq/Msgq.go:492 +0x2a
created by github.com/qydysky/part/msgq.(*MsgType[...]).Pull_tag_async.func1
	/home/runner/go/pkg/mod/github.com/qydysky/part@v0.28.1-0.20230726013256-40eba56c6e85/msgq/Msgq.go:491 +0x15b
```

**Comment by qydysky** [comment]
初步分析，PushBack时，lock失效导致
在 https://github.com/qydysky/part/commit/445f3ba32ca26b2ac95aab69f9053fcfbc4c5cab 对读写锁进行重写
